# Table Extraction

## Basic Table Extraction

In [ ]:
%pip install pandas
# %pip install lxml

In [14]:
import pandas as pd

In [15]:
bleach = pd.read_html('https://en.wikipedia.org/wiki/List_of_Bleach_episodes')

In [16]:
print("Number of tables extracted: ",len(bleach))

Number of tables extracted:  42

In [17]:
bleach[1]

,No.,Title,Storyboarded by,Directed by,Written by,Original air date,English air date
0,1,"""The Day I Became a Shinigami"" Transliteration...",Noriyuki Abe,Noriyuki Abe,Masashi Sogo,"October 5, 2004","September 10, 2006"
1,2,"""A Shinigami's Work"" Transliteration: ""Shiniga...",Jun'ya Koshiba,Jun'ya Koshiba,Natsuko Takahashi,"October 12, 2004","September 17, 2006"
2,3,"""The Older Brother's Wish, the Younger Sister'...",Noriyuki Abe,Shigeki Hatakeyama,Natsuko Takahashi,"October 19, 2004","September 24, 2006"
3,4,"""Cursed Parakeet"" Transliteration: ""Noroi no I...",Hidehito Ueda,Takuji Kimura,Genki Yoshimura,"October 26, 2004","October 1, 2006"
4,5,"""Beat the Invisible Enemy!"" Transliteration: ""...",Tetsuhito Saitō,Kazunori Mizuno,Genki Yoshimura,"November 2, 2004","October 8, 2006"
5,6,"""Fight to the Death! Ichigo vs. Ichigo"" Transl...",Motosuke Takahashi,Jun'ya Koshiba,Michiko Yokote,"November 9, 2004","October 15, 2006"
6,7,"""Greetings from a Stuffed Lion"" Transliteratio...",Motosuke TakahashiShigeki Hatakeyama,Akira Shimizu,Michiko YokoteMasashi Sogo,"November 16, 2004","October 22, 2006"
7,8,"""June 17, Memories in the Rain"" Transliteratio...",Noriyuki Abe,Shigeki Hatakeyama,Masashi Sogo,"November 23, 2004","October 29, 2006"
8,9,"""Unbeatable Enemy"" Transliteration: ""Taosenai ...",Sanzō Tsunoda,Takuji Kimura,Masashi Sogo,"November 30, 2004","November 5, 2006"
9,10,"""Assault on Trip at Sacred Ground!"" Transliter...",Kazunori Mizuno,Kazunori Mizuno,Masahiro Ōkubo,"December 7, 2004","November 12, 2006"
10,11,"""The Legendary Quincy"" Transliteration: ""Dense...",Jun'ya Koshiba,Jun'ya Koshiba,Michiko Yokote,"December 14, 2004","November 19, 2006"
11,12,"""A Gentle Right Arm"" Transliteration: ""Yasashi...",Kōji Aritomi,Kōji Aritomi,Genki Yoshimura,"December 21, 2004","November 26, 2006"
12,13,"""Flower and Hollow"" Transliteration: ""Hana to ...",Sanzō Tsunoda,Takuji Kimura,Natsuko Takahashi,"December 28, 2004","December 3, 2006"
13,14,"""Back to Back, a Fight to the Death!"" Translit...",Tetsuhito Saitō,Noriyuki Abe,Masashi Sogo,"January 11, 2005","December 10, 2006"
14,15,"""Kon's Great Plan"" Transliteration: ""Kon no Uh...",Chiaki Kon,Chiaki Kon,Masahiro Ōkubo,"January 18, 2005","December 17, 2006"
15,16,"""The Encounter, Abarai Renji!"" Transliteration...",Motosuke Takahashi,Jun'ya Koshiba,Michiko Yokote,"January 25, 2005","January 7, 2007"
16,17,"""Ichigo Dies!"" Transliteration: ""Ichigo, Shisu...",Manabu Fukazawa,Kazunori Mizuno,Rika Nakase,"February 1, 2005","January 14, 2007"
17,18,"""Reclaim! The Power of the Shinigami!"" Transli...",Jun'ya Koshiba,Akira Shimizu,Natsuko Takahashi,"February 8, 2005","January 21, 2007"
18,19,"""Ichigo Becomes a Hollow!"" Transliteration: ""I...",Tetsuhito Saitō,Takuji Kimura,Genki Yoshimura,"February 15, 2005","January 28, 2007"
19,20,"""Ichimaru Gin's Shadow"" Transliteration: ""Ichi...",Shigeki Hatakeyama,Shigeki Hatakeyama,Masashi Sogo,"February 22, 2005","February 4, 2007"

## Extracting CSV files from Websites and PDF file

Target Website: [https://www.football-data.co.uk/data.php](https://www.football-data.co.uk/data.php)

In [19]:
df_premier24= pd.read_csv('https://www.football-data.co.uk/mmz4281/2425/E0.csv')

In [20]:
df_premier24

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,E0,15/12/2024,14:00,Brighton,Crystal Palace,1,3,A,0,2,...,1.97,1.96,1.93,2.00,1.97,2.01,1.90,1.96,1.96,2.03
155,E0,15/12/2024,16:30,Man City,Man United,1,2,A,1,0,...,2.05,1.75,2.11,1.81,2.34,1.86,2.11,1.77,2.11,1.88
156,E0,15/12/2024,19:00,Chelsea,Brentford,2,1,H,1,0,...,1.91,2.02,1.88,2.04,1.99,2.04,1.93,1.94,2.01,1.98
157,E0,15/12/2024,19:00,Southampton,Tottenham,0,5,A,0,5,...,1.95,1.98,1.94,1.98,2.04,2.02,1.92,1.94,1.99,1.99
158,E0,16/12/2024,20:00,Bournemouth,West Ham,1,1,D,0,0,...,1.99,1.91,2.00,1.93,2.02,2.03,1.92,1.94,1.93,2.04

In [21]:
df_premier24.rename(columns={'FTHG':'home_goals','FTAG':'away_goals'},inplace=True)

In [23]:
df_premier24.head()

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10

Extracting Table for a PDF file
Install the following dependencies before install the main package 'camelot-py':
```bash
pip install tk
pip install ghostscript
pip install opencv-python
pip install camelot-py

```

In [3]:
import camelot

In [4]:
tables = camelot.read_pdf('assests/pdfs/foo.pdf',pages= '1')

print(tables)

<TableList n=1>

In [5]:
tables.export('foo.csv',f='csv',compress=True)
tables[0].to_csv('foo.csv')